#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

#hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r spawn ~/bin/vgatoggle.sh
#hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-space spawn ~/bin/yeganesh.sh

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Shift-u spawn ~/bin/herbstluftwm/hlwm_new_frame_move.sh bottom 0.5
hc keybind $Mod-Shift-o spawn ~/bin/herbstluftwm/hlwm_new_frame_move.sh right  0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# non-wm related keybinds
hc keybind XF86AudioRaiseVolume spawn sh -c "pactl set-sink-volume @DEFAULT_SINK@ -- +4%; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86AudioLowerVolume spawn sh -c "pactl set-sink-volume @DEFAULT_SINK@ -- -4%; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86AudioMute spawn sh -c "pactl set-sink-mute @DEFAULT_SINK@ toggle; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86MonBrightnessUp spawn sudo /usr/bin/brightness.sh mon \*2
hc keybind XF86MonBrightnessDown spawn sudo /usr/bin/brightness.sh mon /2
hc keybind XF86KbdBrightnessUp spawn sudo /usr/bin/brightness.sh kbd +50
hc keybind XF86KbdBrightnessDown spawn sudo /usr/bin/brightness.sh kbd -50
hc keybind XF86LaunchA spawn touchpadtoggle
hc keybind $Mod-Shift-x spawn /usr/bin/i3lock -u -c 9a875f
hc keybind $Mod-Shift-s spawn /usr/bin/systemctl suspend
#hc keybind XF86AudioPlay spawn /usr/bin/ncmpcpp toggle
#hc keybind XF86AudioStop spawn /usr/bin/ncmpcpp stop
#hc keybind XF86AudioPrev spawn /usr/bin/ncmpcpp prev
#hc keybind XF86AudioNext spawn /usr/bin/ncmpcpp next
hc keybind $Mod-Shift-b spawn xdotool search --onlyvisible "Chromium" windowfocus --sync key XF86AudioPrev
hc keybind $Mod-Shift-m spawn xdotool search --onlyvisible "Chromium" windowfocus --sync key XF86AudioNext
hc keybind $Mod-Shift-w spawn xdotool search --onlyvisible "Chromium" windowfocus --sync key XF86AudioPlay

# tags
tag_names=( 1:main 2:web 3:chat 4:gui 5:games 6:misc )
tag_keys=( {1..9} 0 )

hc set default_frame_layout 1
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
hc set_layout horizontal

# cycle through tags
hc keybind $Mod-BackSpace use_index +1 --skip-visible
hc keybind $Mod-Shift-BackSpace  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-space cycle_layout -1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-comma   cycle_monitor -1
hc keybind $Mod-period   cycle_monitor +1
hc keybind $Mod-Shift-comma   spawn ~/bin/herbstluftwm/hlwm_swap_monitors.sh -1
hc keybind $Mod-Shift-period   spawn ~/bin/herbstluftwm/hlwm_swap_monitors.sh +1
hc keybind $Mod-Control-comma   spawn ~/bin/herbstluftwm/hlwm_shift_to_monitor.sh -1
hc keybind $Mod-Control-period   spawn ~/bin/herbstluftwm/hlwm_shift_to_monitor.sh +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# colors
hc set frame_border_active_color '#000000'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#222222'
hc set frame_border_width 1
hc set window_border_width 5
hc set window_border_inner_width 1
hc set window_border_normal_color '#181512'
hc set window_border_active_color '#d0d0d0'
hc set window_border_urgent_color '#882020'
hc set always_show_frame 1
hc set frame_bg_transparent 0
hc set frame_active_opacity 75
hc set frame_normal_opacity 75
hc set frame_transparent_width 5
hc set frame_gap 30
hc set gapless_grid 1
# add overlapping window borders
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 1
hc set auto_detect_monitors 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
#hc rule focus=off # normally do not focus new clients
hc rule focus=on # normally do focus new clients
# give focus to most common terminals
# web
hc rule class~'(Chromium)' tag="${tag_names[1]}"
# gui
hc rule class~'(Soffice|LibreOffice|.*libreoffice.*)' tag="${tag_names[3]}"
hc rule class~'(Apvlv|Thunderbird|Mumble)' tag="${tag_names[3]}"
hc rule class~'(Gimp|Inkscape)' tag="${tag_names[3]}"
# games
hc rule class~'(Steam)' tag="${tag_names[4]}"
hc rule class~'(.*(M|m)inecraft.*)' tag="${tag_names[4]}"
hc rule class~'(Hedgewars|hwengine)' tag="${tag_names[4]}" fullscreen=on
hc rule class~'(teeworlds)' tag="${tag_names[4]}" fullscreen=on
hc rule class~'(Dolphin-emu)' tag="${tag_names[4]}" fullscreen=on
hc rule class~'(.*ioquake.*)' tag="${tag_names[4]}" fullscreen=on
# misc
hc rule class~'xbmc\.bin' tag="${tag_names[5]}" fullscreen=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

avant-window-navigator &


if [[ $HOSTNAME == "servy" ]]; then
	tmux source-file ~/.tmux.servy
	hc set window_border_active_color '#181512'
	hc set frame_bg_active_color '#000000'
fi
