#!/bin/bash

# herbstluftwm config

hc() {
    herbstclient "$@"
}

xftfont=$($HOME/bin/theme.sh xftfont)
active_bg=\#$($HOME/bin/theme.sh bg)
active_fg=\#$($HOME/bin/theme.sh active_fg)
inactive_bg=\#$($HOME/bin/theme.sh bg)
inactive_fg=\#$($HOME/bin/theme.sh inactive_fg)

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close
hc keybind $Mod-Return spawn urxvt
#hc keybind $Mod-space spawn dmenu_run -fn "$xftfont" -p run: -nb $inactive_bg -nf $inactive_fg -sb $active_bg -sf $active_fg -hist $HOME/.cache/dmenu_run_hist
hc keybind $Mod-space spawn rofi -show run -font "Droid Sans 10"

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u spawn ~/bin/herbstluftwm/hlwm_new_frame_move.sh bottom 0.5
hc keybind $Mod-o spawn ~/bin/herbstluftwm/hlwm_new_frame_move.sh right  0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# non-wm related keybinds
hc keybind XF86AudioRaiseVolume spawn sh -c "pactl set-sink-volume @DEFAULT_SINK@ +4%; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86AudioLowerVolume spawn sh -c "pactl set-sink-volume @DEFAULT_SINK@ -4%; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86AudioMute spawn sh -c "pactl set-sink-mute @DEFAULT_SINK@ toggle; paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
hc keybind XF86MonBrightnessUp spawn sudo /usr/bin/brightness.sh mon \*2
hc keybind XF86MonBrightnessDown spawn sudo /usr/bin/brightness.sh mon /2
hc keybind XF86KbdBrightnessUp spawn sudo /usr/bin/brightness.sh kbd +50
hc keybind XF86KbdBrightnessDown spawn sudo /usr/bin/brightness.sh kbd -50
hc keybind XF86LaunchA spawn touchpadtoggle
hc keybind $Mod-Shift-x spawn /home/rasse/bin/lock
hc keybind $Mod-Shift-s spawn /usr/bin/systemctl suspend
hc keybind XF86AudioPlay spawn /home/rasse/src/nodeplayer-client/index.js -k
hc keybind XF86AudioStop spawn /home/rasse/src/nodeplayer-client/index.js -u
hc keybind XF86AudioPrev spawn /home/rasse/src/nodeplayer-client/index.js -g-1
hc keybind XF86AudioNext spawn /home/rasse/src/nodeplayer-client/index.js -g 1
hc keybind $Mod-Shift-b spawn xdotool key XF86AudioPrev
hc keybind $Mod-Shift-m spawn xdotool key XF86AudioNext
hc keybind $Mod-Shift-w spawn xdotool key XF86AudioPlay

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} )

hc set default_frame_layout 2
hc set_layout max
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" spawn ~/bin/herbstluftwm/hlwm_focus_monitor_byname.sh "monitor$key"
        hc keybind "$Mod-Control-$key" spawn ~/bin/herbstluftwm/hlwm_use_mtag.sh "$key"
        hc keybind "$Mod-Shift-$key" spawn ~/bin/herbstluftwm/hlwm_mv_mtag.sh "$key"
    fi
done
hc keybind "$Mod-n" spawn ~/bin/herbstluftwm/hlwm_new_tag.sh
hc keybind "$Mod-Shift-n" spawn ~/bin/herbstluftwm/hlwm_new_tag_move.sh

# cycle through tags
hc keybind $Mod-Tab spawn ~/bin/herbstluftwm/hlwm_cycle_tags.sh +1
hc keybind $Mod-Shift-Tab spawn ~/bin/herbstluftwm/hlwm_cycle_tags.sh -1
hc keybind $Mod-Control-Tab  use_previous

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-space cycle_layout -1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
#hc keybind $Mod-comma   cycle_monitor -1
#hc keybind $Mod-period   cycle_monitor +1
#hc keybind $Mod-Control-comma   spawn ~/bin/herbstluftwm/hlwm_swap_monitors.sh -1
#hc keybind $Mod-Control-period   spawn ~/bin/herbstluftwm/hlwm_swap_monitors.sh +1
#hc keybind $Mod-Shift-comma   spawn ~/bin/herbstluftwm/hlwm_shift_to_monitor.sh -1
#hc keybind $Mod-Shift-period   spawn ~/bin/herbstluftwm/hlwm_shift_to_monitor.sh +1
hc keybind Alt-Shift-Tab   cycle_all -1
hc keybind Alt-Tab         cycle_all +1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# colors
hc set frame_border_active_color '#000000'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color \#$($HOME/bin/theme.sh inactive_bg)
hc set frame_bg_active_color \#$($HOME/bin/theme.sh active_bg)
hc set frame_border_width 0
hc set window_border_width 4
hc set window_border_inner_width 0
hc set window_border_normal_color \#$($HOME/bin/theme.sh inactive_border)
hc set window_border_active_color \#$($HOME/bin/theme.sh active_border)
hc set window_border_urgent_color \#$($HOME/bin/theme.sh urgent_border)
hc set always_show_frame 1
hc set frame_gap $($HOME/bin/theme.sh frame_gap)
hc set gapless_grid 0
# add overlapping window borders
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set auto_detect_monitors 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
#hc rule focus=off # normally do not focus new clients
hc rule focus=on # normally do focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

# unlock, just to be sure
hc unlock

# monitors
# give monitors a name from monitor{1..9}
hc detect_monitors
if [[ $HOSTNAME == "bulky" ]]; then
    hc rename_monitor 1 monitor1
    hc rename_monitor 2 monitor2
    hc rename_monitor 0 monitor3
else
    for i in $(hc list_monitors | cut -d':' -f1); do
        hc rename_monitor $i monitor$((i+1))
    done
fi

herbstclient set tree_style '╾│ ├└╼─┐'

if [[ $HOSTNAME == "servy" ]]; then
	tmux source-file ~/.tmux.servy
	hc set window_border_active_color '#181512'
	hc set frame_bg_active_color '#000000'
fi
