#! /bin/zsh
#unset DBUS_SESSION_BUS_ADDRESS
#compton --config ~/.config/compton.conf &

bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc desktop mon1 -l monocle
#bspc desktop ^2 -l monocle

bspc rule -a Steam -d 5
bspc rule -a Firefox -d 2
#--follow
#
bspc rule -a BSPWM_FRAME --frame
bspc config normal_frame_opacity 0

bspc config split_ratio             0.50
bspc config border_width            1
bspc config window_gap              30
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config auto_cancel 			true
bspc config normal_border_color     "#181512"
bspc config focused_border_color    "#88ada9"
bspc config presel_border_color     "#c87d79"

if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi
